version: "3.8"

services:
  djangoCatalog:
    build:
      context: .
      dockerfile: ./compose/base/Dockerfile
    env_file:
      - .env
    image: movie_catalog
    command: sh /usr/src/app/compose/local/start.sh
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    depends_on:
      - postgresCatalog
      - redisCatalog
    restart: always
    networks:
      - movie_network

  postgresCatalog:
    image: postgres
    ports:
      - "5444:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - movie_network

  redisCatalog:
    image: redis
    ports:
      - "6378:6379"
    restart: always
    networks:
      - movie_network

networks:
  movie_network:
    external: true