# Generated by Django 3.2 on 2022-03-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalog",
            old_name="contents_ids",
            new_name="contents",
        ),
    ]
